[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm exec nx run-many -t build"]

[start]
cmd = "cd backend && npx tsx src/database/migrate.ts; cd .. && node backend/dist/index.js"

[variables]
NODE_ENV = "production"
